uses
  ascii,     { Constants for various ASCII characters and keyboard scan codes }
  consts,    { Multiple useful typed and untyped constants }
  datetime,  { Data types and datetime handling routines }
  debug,     { Used to show debug information }
  locale,    { Contains localized strings used all over the library. }
  math,      { All things about numbers }
  strings,   { Pascal and null-terminated string manipulation }
  types,     { Common types used in multiple units, put here for convenience }
  palette,   { All about color palettes! }
  utils,     { Stuff that doesn't fit anywhere else: type conversions, compare functions }
  xcrt;      { A smaller and hopefully less buggy replacement for Borland's CRT unit }

begin
end.